### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by eeee920** [heunetik/gladiatusScript#1]
hey its not working 

how can i contact you :(

**Comment by heunetik** [comment]
It is not currently updated to the game's latest version, and there are no plans to update it in the near future.
The development shifted towards a Chrome extension that will be able to do everything this script does, and more.

If I'll have a bit of spare time, I might go over it, and fix it up, but the project is no longer maintained, so there will not be any update consistency.

**Comment by eeee920** [comment]
i just need pve expeditions factory 
im farming Tatzelwurm in germenia 
can you do it in an empty time? <3
